FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt locust

COPY tests/locust /mnt/locust

EXPOSE 8089

ENTRYPOINT ["locust"]